spring.application.name=message_queue
server.port=8082

# PostgreSQL DB
spring.datasource.url=jdbc:postgresql://localhost:5432/mqdb
spring.datasource.username=postgres
spring.datasource.password=Vidhanshu@37

spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health,info
mq.data.dir=/tmp/mq-data

broker.id=broker-1
broker.host=localhost
broker.port=${server.port:8082}

# All peers in the cluster (every broker lists ALL addresses including its own -
# BrokerStartupConfig will exclude self automatically)
cluster.peers=localhost:8082,localhost:8083,localhost:8084

# Replication settings
replication.factor=3
replication.timeout.ms=5000